recipebook/recipebook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("recipes.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("mdeditor/", include("mdeditor.urls")),
]

if settings.MEDIA_URL:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

recipebook/users/urls.py
from django.contrib.auth import views
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.urls import path, reverse_lazy

from core.forms import add_styles_to_form
from users import views as u_views

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        u_views.SignUpView.as_view(),
        name="signup",
    ),
    path(
        "profile/",
        u_views.ProfileView.as_view(),
        name="profile",
    ),
    path(
        "activate/<uidb64>/<token>",
        u_views.ActivateView.as_view(),
        name="activate",
    ),
    path(
        "activate/",
        u_views.ActivateDoneView.as_view(),
        name="activate_done",
    ),
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
            form_class=add_styles_to_form(AuthenticationForm),
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
            form_class=add_styles_to_form(PasswordChangeForm),
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
            form_class=add_styles_to_form(PasswordResetForm),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
            form_class=add_styles_to_form(SetPasswordForm),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]


__all__ = []

recipebook/templates/includes/footer.html
{% load static %}
{% load i18n %}
<footer class="footer mt-3 py-3 bg-light">
    <div class="container">
        <form action="{% url 'set_language' %}" method="post" class="d-inline-flex ">
		{% csrf_token %}
		<input name="next" type="hidden" value="{{ redirect_to }}">
		<select name="language" class="form-select">
			{% get_current_language as LANGUAGE_CODE %}
			{% get_available_languages as LANGUAGES %}
			{% get_language_info_list for LANGUAGES as languages %}
			{% for language in languages %}
				<option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
					{{ language.name_local }} ({{ language.code }})
				</option>
			{% endfor %}
		</select>
		<button type="submit" class="btn btn-primary">{% translate "footer__set_lang" %}</button>
	</form>
    </div>

</footer>

recipebook/templates/includes/form.html
{% load i18n %}
{% load add_attr %}
{% comment %} vars: form, inner, submit_text {% endcomment %}
{% if not inner %}
<form method="POST" {% if action %}action="{{action}}"{% endif %}>
	{% csrf_token %}
{% endif %}

	{% for hidden_field in form.hidden_fields %}
	{{ hidden_field }}
	{% endfor %}

	{% if form.non_field_errors %}
	<div class="alert alert-danger" role="alert">
		{% for error in form.non_field_errors %}
		<div>{{ error }}</div>
		{% endfor %}
	</div>
	{% endif %}

	{% for field in form.visible_fields %}
	<div class="mb-3 {% if field.widget_type == 'checkbox' %}form-check{% endif %}">
		<label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>

		{% if form.is_bound %}
			{% if field.errors %}
				{{ field | add_attr:"is-invalid" }}
				{% for error in field.errors %}
				<div class="invalid-feedback">
					{{ error }}
				</div>
				{% endfor %}
			{% else %}
				{{ field | add_attr:"is-valid" }}
			{% endif %}
		{% else %}
			{{ field }}
		{% endif %}

		{% if field.help_text %}
		<div class="form-text">{{ field.help_text }}</div>
		{% endif %}
	</div>
	{% endfor %}
{% if not inner %}
<button type="submit" class="btn btn-primary">{% if submit_text %}{{submit_text}}{% else %}{% translate "form__send" %}{% endif %}</button>
</form>
{% endif %}

recipebook/templates/includes/header.html
{% load static %}
{% load i18n %}
<header>
	<nav class="navbar navbar-expand-md fixed-top bg-light">
		<div class="container-fluid container">
			<a href="/" class="d-flex align-items-center text-dark text-decoration-none">
				<img src="{% static 'img/icon48.png' %}" alt="logo" class="rounded me-2">
				<span class="navbar-brand">{% translate "title" %}</span>
			</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
				aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			{% with request.resolver_match.view_name as view_name %}
			<div class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav me-auto mb-2 mb-md-0">
					<li class="nav-item">
						<a class="nav-link {% if view_name == 'recipes:recipe-add' %}active{% endif %}"
							href="{% url 'recipes:recipe-add' %}">{% translate "nav_menu__add_recipe" %}</a>
					</li>
					{% if user.is_superuser %}
					<li class="nav-item">
						<a class="nav-link"
							href="{% url 'admin:index' %}">{% translate "nav_menu__admin" %}</a>
					</li>
					{% endif %}
				</ul>
				{% if user.is_authenticated %}
					<div class="dropdown">
						<a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
							{% if user.image %}
							<img src="{{user.get_image_32x32.url}}" alt="{{user.name}}" width="32" height="32" class="rounded-circle">
							{% endif %}
							<span class="mx-1">{{user.username}}</span>
						</a>
						<ul class="dropdown-menu text-small" style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate(0px, 34px);">
							<li><a class="dropdown-item" href="{% url 'users:profile' %}">{% translate "header__user__profile" %}</a></li>
							<li><a class="dropdown-item" href="{% url 'users:password_change' %}">{% translate "header__user__change_password" %}</a></li>
							<li><hr class="dropdown-divider"></li>
							<li><a class="dropdown-item" href="{% url 'users:logout' %}">{% translate "header__user__logout" %}</a></li>
						</ul>
					</div>
				{% else %}
					<div>
						{% if view_name != "users:login" %}
						<a type="button" class="btn btn-outline-primary me-2" href="{% url 'users:login' %}">{% translate "header__user__login" %}</a>
						{% endif %}
						{% if view_name != "users:signup" %}
						<a type="button" class="btn btn-primary me-2" href="{% url 'users:signup' %}">{% translate "header__user__signup" %}</a>
						{% endif %}
					</div>
				{% endif %}
			</div>
			{% endwith %}
		</div>
	</nav>
</header>