recipebook/recipebook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("recipes.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("mdeditor/", include("mdeditor.urls")),
]

if settings.MEDIA_URL:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

recipebook/users/urls.py
from django.contrib.auth import views
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.urls import path, reverse_lazy

from core.forms import add_styles_to_form
from users import views as u_views

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        u_views.SignUpView.as_view(),
        name="signup",
    ),
    path(
        "profile/",
        u_views.ProfileView.as_view(),
        name="profile",
    ),
    path(
        "activate/<uidb64>/<token>",
        u_views.ActivateView.as_view(),
        name="activate",
    ),
    path(
        "activate/",
        u_views.ActivateDoneView.as_view(),
        name="activate_done",
    ),
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
            form_class=add_styles_to_form(AuthenticationForm),
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
            form_class=add_styles_to_form(PasswordChangeForm),
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
            form_class=add_styles_to_form(PasswordResetForm),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
            form_class=add_styles_to_form(SetPasswordForm),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]


__all__ = []

recipebook/users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager as BaseUserManager
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from sorl.thumbnail import get_thumbnail

from core.utils import RandomFileName, Thumbnail


class UserManager(BaseUserManager):
    @classmethod
    def normalize_email(cls, email: str | None) -> str:
        email = super().normalize_email(email)
        if "@" not in email:
            return email

        email = email.lower()
        username, domain = email.split("@")

        if domain == "ya.ru":
            domain = "yandex.ru"

        if "+" in username:
            username = username.split("+")[0]

        if domain == "gmail.com":
            username = username.replace(".", "")

        if domain == "yandex.ru":
            username = username.replace(".", "-")

        return f"{username}@{domain}"

    def active(self) -> models.query.QuerySet:
        return self.get_queryset().filter(is_active=True)

    def by_mail(self, mail: str) -> "User | None":
        mail = self.normalize_email(mail)
        try:
            return self.get_queryset().get(email=mail)
        except User.DoesNotExist:
            return None

    def by_username(self, username: str) -> "User | None":
        try:
            return self.get_queryset().get(username=username)
        except User.DoesNotExist:
            return None


class User(AbstractUser):
    objects: UserManager["User"] = UserManager()

    email = models.EmailField(
        verbose_name=_("users__model__user__email"),
        unique=True,
    )
    image = models.ImageField(
        verbose_name=_("users__model__user__image"),
        upload_to=RandomFileName("users/image/"),
        null=True,
        blank=True,
    )
    trusted = models.BooleanField(
        verbose_name=_("users__model__user__trusted"),
        default=False,
    )
    attempts_count = models.PositiveIntegerField(
        verbose_name=_("users__model__user__attempts_count"),
        default=0,
    )
    deactivation_date = models.DateTimeField(
        verbose_name=_("users__model__user__deactivation_date"),
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _("users__model__user__verbose_name")
        verbose_name_plural = _(
            "users__model__user__verbose_name_plural",
        )

    def get_image_32x32(self) -> Thumbnail | None:
        if not self.image:
            return None

        return get_thumbnail(
            self.image,
            "32x32",
            crop="center",
            quality=85,
            format="PNG",
        )

    def get_image_128x128(self) -> Thumbnail | None:
        if not self.image:
            return None

        return get_thumbnail(
            self.image,
            "128x128",
            crop="center",
            quality=85,
            format="PNG",
        )

    def image_tmb(self) -> str:
        if self.image:
            return mark_safe(
                f'<img src="{self.get_image_128x128().url}"',
            )

        return _("model__image__no_image")

    image_tmb.short_description = _("model__image__preview")
    image_tmb.allow_tags = True


__all__ = []

recipebook/users/forms.py
from typing import Any

from django import forms
from django.contrib.auth.forms import UserCreationForm

from core.forms import BaseForm
from users import models


class SignUpForm(UserCreationForm, BaseForm):
    def clean(self) -> dict[str, Any]:
        email = self.cleaned_data[models.User.email.field.name]
        email = models.UserManager.normalize_email(email)
        self.cleaned_data[models.User.email.field.name] = email

        return self.cleaned_data

    class Meta(UserCreationForm.Meta):
        model = models.User
        fields = [
            models.User.username.field.name,
            models.User.email.field.name,
        ]


class UserForm(forms.ModelForm, BaseForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields[models.User.trusted.field.name].disabled = True
        self.fields[models.User.email.field.name].disabled = True

    class Meta:
        model = models.User
        fields = [
            models.User.first_name.field.name,
            models.User.last_name.field.name,
            models.User.email.field.name,
            models.User.trusted.field.name,
            models.User.image.field.name,
        ]


__all__ = []

recipebook/users/views.py
from datetime import timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.translation import gettext
from django.views.generic import FormView, TemplateView, UpdateView, View

from users.forms import SignUpForm, UserForm
from users.models import User


class SignUpView(FormView):
    template_name = "users/signup.html"
    form_class = SignUpForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form: SignUpForm) -> HttpResponse:
        user = form.save(commit=False)
        user.is_active = settings.DEFAULT_USER_IS_ACTIVE
        user.save()

        current_site = get_current_site(self.request)
        site_name = current_site.name
        domain = current_site.domain
        use_https = self.request.is_secure()
        email = form.cleaned_data["email"]
        mail_context = {
            "username": form.cleaned_data["username"],
            "domain": domain,
            "site_name": site_name,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": default_token_generator.make_token(user),
            "protocol": "https" if use_https else "http",
        }
        send_mail(
            gettext("signup__mail__subject"),
            render_to_string("users/signup_email.html", mail_context),
            None,
            [email],
            fail_silently=False,
        )
        messages.success(
            self.request,
            gettext("signup__success_message") % {"email": email},
        )
        return super().form_valid(form)


class ActivateView(View):
    def get(
        self,
        request: HttpRequest,
        uidb64: str,
        token: str,
    ) -> HttpResponse:
        user = get_user(uidb64)

        if user is None or not default_token_generator.check_token(
            user,
            token,
        ):
            messages.error(request, gettext("activate__error_message"))
            return redirect(reverse("users:activate_done"))

        if user.deactivation_date:
            if user.deactivation_date < timezone.now() - timedelta(
                days=7,
            ):
                messages.error(request, gettext("activate__old_message"))
                return redirect(reverse("users:activate_done"))
        elif user.date_joined < timezone.now() - timedelta(hours=12):
            messages.error(request, gettext("activate__old_message"))
            return redirect(reverse("users:activate_done"))

        user.is_active = True
        user.save()

        messages.success(request, gettext("activate__success_message"))
        return redirect(reverse("users:activate_done"))


class ActivateDoneView(TemplateView):
    template_name = "users/activate_done.html"


class ProfileView(LoginRequiredMixin, UpdateView):
    template_name = "users/profile.html"
    form_class = UserForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset: QuerySet | None = None) -> User:
        return self.request.user

    def form_valid(self, form: UserForm) -> HttpResponse:
        messages.success(self.request, gettext("profile__success_message"))
        return super().form_valid(form)


def get_user(uidb64: str) -> User | None:
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        return User.objects.get(pk=uid)
    except Exception:
        return None


__all__ = []

recipebook/templates/users/activate_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% translate "activate_done__title" %}
{% endblock %}

{% block content %}
	<h3 class="text-center mt-4">{% translate "activate_done__title" %}</h3>

	<div class="row justify-content-center">
		<div class="col-12 col-md-8 col-lg-6">
			{% if messages %}
				{% for message in messages %}
					<div class="alert {% if message.tags == 'success' %}alert-success{% endif %} {% if message.tags == 'error' %}alert-danger{% endif %}">
						<span>{{ message }}</span>
					</div>
				{% endfor %}
			{% endif %}
		</div>
	</div>
{% endblock %}

recipebook/templates/users/deactivation_email.html
{% load i18n %}{% autoescape off %}
{% translate "signup_email__greet" %} {{ username }}!

{% translate "deactivation_email__text" %}
{{ protocol }}://{{ domain }}{% url "users:activate" uidb64=uid token=token %}

{% translate "password_reset_email__thanks" %}

{% blocktranslate %}password_reset_email__team {{ site_name }}{% endblocktranslate %}

{% endautoescape %}

recipebook/templates/users/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% translate "login__title" %}
{% endblock %}

{% block content %}
	<h2 class="text-center mt-4">{% translate "login__title" %}</h2>

	<div class="row justify-content-center">
		<div class="col-12 col-md-6 col-lg-4">
			{% if messages %}
				{% for message in messages %}
					<div class="alert {% if message.tags == 'success' %}alert-success{% endif %}">
						<span>{{ message }}</span>
					</div>
				{% endfor %}
			{% endif %}
			{% translate "login__submit" as submit %}
			{% include "includes/form.html" with form=form submit_text=submit %}
			<a class="link d-block mt-4" href="{% url 'users:password_reset' %}">{% translate "signup__reset_password" %}</a>
		</div>
	</div>
{% endblock %}

recipebook/templates/users/password_change.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% translate "password_change__title" %}
{% endblock %}

{% block content %}
	<h2 class="text-center mt-4">{% translate "password_change__title" %}</h2>

	<div class="row justify-content-center">
		<div class="col-12 col-md-6 col-lg-4">
			{% translate "password_change__submit" as submit %}
			{% include "includes/form.html" with form=form submit_text=submit %}
		</div>
	</div>
{% endblock %}

recipebook/templates/users/password_change_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% translate "password_change_done__title" %}
{% endblock %}

{% block content %}
	<h2 class="text-center mt-4">{% translate "password_change_done__title" %}</h2>
{% endblock %}

recipebook/templates/users/password_reset.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% translate "password_reset__title" %}
{% endblock %}

{% block content %}
	<h2 class="text-center mt-4">{% translate "password_reset__title" %}</h2>
	<div class="row justify-content-center">
		<div class="col-12 col-md-6 col-lg-4">
			<p>{% translate "password_reset__hint" %}</p>
			{% translate "password_reset__submit" as submit %}
			{% include "includes/form.html" with form=form submit_text=submit %}
		</div>
	</div>
{% endblock %}

recipebook/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% translate "password_reset_complete__title" %}
{% endblock %}

{% block content %}
	<div class="row justify-content-center mb-4">
		<div class="col-12 col-md-8 col-lg-6">
			<h4>{% translate "password_reset_complete__text" %}</h4>
			<p><a class="btn btn-primary" href="{{ login_url }}">{% translate "password_reset_complete__login" %}</a></p>
		</div>
	</div>
{% endblock %}

recipebook/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% load add_attr %}

{% block title %}
{% translate "password_reset_confirm__title" %}
{% endblock %}

{% block content %}
	{% if validlink %}

	<div class="row justify-content-center mb-4">
		<div class="col-12 col-md-8 col-lg-6">
			<h4>{% translate "password_reset_confirm__text" %}</h4>
		</div>
	</div>

	<div class="row justify-content-center">
		<div class="col-12 col-md-6 col-lg-4">
			<form method="post">{% csrf_token %}
				<input class="d-none" autocomplete="username" value="{{ form.user.get_username }}">
				<div class="mb-3">
					<label for="id_new_password1" class="form-label">{% translate "password_reset_confirm__new_password" %}</label>
					{% if form.new_password1.errors %}
						{{ form.new_password1 | add_attr:"is-invalid" }}
						{% for error in form.new_password1.errors %}
						<div class="invalid-feedback">
							{{ error }}
						</div>
						{% endfor %}
					{% else %}
					{{ form.new_password1 }}
					{% endif %}
				</div>
				<div class="mb-3">
					<label for="id_new_password2" class="form-label">{% translate "password_reset_confirm__confirm_password" %}</label>
					{% if form.new_password2.errors %}
						{{ form.new_password2 | add_attr:"is-invalid" }}
						{% for error in form.new_password2.errors %}
						<div class="invalid-feedback">
							{{ error }}
						</div>
						{% endfor %}
					{% else %}
					{{ form.new_password2 }}
					{% endif %}
				</div>
				<button type="submit" class="btn btn-primary">{% translate "password_reset_confirm__change_password" %}</button>
			</form>
		</div>
	</div>


	{% else %}

	<div class="row justify-content-center">
		<div class="col-12 col-md-8 col-lg-6">
			<h4>{% translate "password_reset_confirm__error" %}</h4>
		</div>
	</div>

	{% endif %}
{% endblock %}

recipebook/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% translate "password_reset_done__title" %}
{% endblock %}

{% block content %}
	<h3 class="text-center mt-4">{% translate "password_reset_done__title" %}</h3>

	<div class="row justify-content-center">
		<div class="col-12 col-md-8 col-lg-6">
			{% translate "password_reset_done__text" %}
		</div>
	</div>
{% endblock %}

recipebook/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}password_reset_email__explain {{ site_name }}{% endblocktranslate %}

{% translate "password_reset_email__please" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url "users:password_reset_confirm" uidb64=uid token=token %}
{% endblock %}
{% translate "password_reset_email__username" %} {{ user.get_username }}

{% translate "password_reset_email__thanks" %}

{% blocktranslate %}password_reset_email__team {{ site_name }}{% endblocktranslate %}

{% endautoescape %}

recipebook/templates/users/profile.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
{% translate "profile__title" %}
{% endblock %}

{% block content %}
	<h2 class="text-center mb-4">{% translate "profile__title" %}</h2>

	<div class="row justify-content-center">
		<div class="col-12 col-md-6 col-lg-4">
			{% if messages %}
				{% for message in messages %}
					<div class="alert {% if message.tags == 'success' %}alert-success{% endif %}">
						<span>{{ message }}</span>
					</div>
				{% endfor %}
			{% endif %}
			<div class="d-flex justify-content-center mb-3">
				{% if user.image %}
				<img src="{{user.get_image_128x128.url}}" alt="{{user.username}}" width="128" height="128" class="rounded-circle flex-shrink-0">
				{% else %}
				<img src="{% static 'img/img.svg' %}" alt="{{user.username}}" width="128" height="128" class="rounded-circle flex-shrink-0">
				{% endif %}
			</div>
			{% translate "profile__submit" as submit_text %}
			<p>Почта: {{ user.email }}</p>
			{% include "includes/form.html" with form=form submit_text=submit_text %}
		</div>
	</div>
{% endblock %}

recipebook/templates/users/signup.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% translate "signup__title" %}
{% endblock %}

{% block content %}
	<h2 class="text-center mt-4">{% translate "signup__title" %}</h2>
	<div class="row justify-content-center">
		<div class="col-12 col-md-6 col-lg-4">
			{% translate "signup__submit" as submit %}
			{% include "includes/form.html" with form=form submit_text=submit %}
		</div>
	</div>
{% endblock %}

recipebook/templates/users/signup_email.html
{% load i18n %}{% autoescape off %}
{% translate "signup_email__greet" %} {{ username }}!

{% translate "signup_email__text" %}
{{ protocol }}://{{ domain }}{% url "users:activate" uidb64=uid token=token %}

{% translate "password_reset_email__thanks" %}

{% blocktranslate %}password_reset_email__team {{ site_name }}{% endblocktranslate %}

{% endautoescape %}