recipebook/recipebook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("recipes.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("mdeditor/", include("mdeditor.urls")),
]

if settings.MEDIA_URL:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

recipebook/recipes/urls.py
from django.urls import path

from recipes import views

app_name = "recipes"

urlpatterns = [
    path(
        "",
        views.MainView.as_view(),
        name="main",
    ),
    path(
        "search/",
        views.SearchView.as_view(),
        name="search",
    ),
    path(
        "recipe/<int:pk>",
        views.RecipeView.as_view(),
        name="recipe",
    ),
    path(
        "recipe/<int:pk>/edit",
        views.RecipeEditView.as_view(),
        name="recipe-edit",
    ),
    path(
        "recipe/add",
        views.RecipeAddView.as_view(),
        name="recipe-add",
    ),
]


__all__ = []

recipebook/users/urls.py
from django.contrib.auth import views
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.urls import path, reverse_lazy

from core.forms import add_styles_to_form
from users import views as u_views

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        u_views.SignUpView.as_view(),
        name="signup",
    ),
    path(
        "profile/",
        u_views.ProfileView.as_view(),
        name="profile",
    ),
    path(
        "activate/<uidb64>/<token>",
        u_views.ActivateView.as_view(),
        name="activate",
    ),
    path(
        "activate/",
        u_views.ActivateDoneView.as_view(),
        name="activate_done",
    ),
    path(
        "login/",
        views.LoginView.as_view(
            template_name="users/login.html",
            form_class=add_styles_to_form(AuthenticationForm),
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="users/password_change.html",
            success_url=reverse_lazy("users:password_change_done"),
            form_class=add_styles_to_form(PasswordChangeForm),
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
            form_class=add_styles_to_form(PasswordResetForm),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
            form_class=add_styles_to_form(SetPasswordForm),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]


__all__ = []

recipebook/recipes/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from mdeditor.fields import MDTextField
from sorl.thumbnail import get_thumbnail


from core.models import NormalizedNameMixin, UniqueNormalizedNameMixin
from core.utils import RandomFileName, render_markdown, Thumbnail
from recipes.managers import RecipeManager
from users.models import User


class RecipeLevel(models.IntegerChoices):
    EASY = 1, _("recipes__level_choices__easy")
    NORMAL = 2, _("recipes__level_choices__normal")
    HARD = 3, _("recipes__level_choices__hard")
    EXTREME = 4, _("recipes__level_choices__extreme")


class IngredientUnit(models.TextChoices):
    G = "G", _("recipes__unit_choices__grams")
    KG = "KG", _("recipes__unit_choices__kilogramme")
    L = "L", _("recipes__unit_choices__litre")
    ML = "ML", _("recipes__unit_choices__millilitre")
    PIECE = "PIECE", _("recipes__unit_choices__piece")
    PINCH = "PINCH", _("recipes__unit_choices__pinch")
    TEASPOON = "TEASPOON", _("recipes__unit_choices__tea_spoon")
    TABLESPOON = "TABLESPOON", _("recipes__unit_choices__table_spoon")
    CUP = "CUP", _("recipes__unit_choices__cup")


class RecipeState(models.TextChoices):
    PUBLISHED = "PUB", _("recipes__recipe_state__published")
    MODERATED = "MOD", _("recipes__recipe_state__moderated")
    REJECTED = "REJ", _("recipes__recipe_state__rejected")


class Category(UniqueNormalizedNameMixin, models.Model):
    name = models.CharField(
        verbose_name=_("recipes__model__category__name"),
        max_length=127,
    )

    class Meta:
        ordering = ["name"]
        verbose_name = _("recipes__model__category__verbose_name")
        verbose_name_plural = _(
            "recipes__model__category__verbose_name_plural",
        )

    def __str__(self):
        return self.name


class Kitchen(UniqueNormalizedNameMixin, models.Model):
    name = models.CharField(
        verbose_name=_("recipes__model__kitchen__name"),
        max_length=127,
    )

    class Meta:
        ordering = ["name"]
        verbose_name = _("recipes__model__kitchen__verbose_name")
        verbose_name_plural = _("recipes__model__kitchen__verbose_name_plural")

    def __str__(self):
        return self.name


class Ingredient(UniqueNormalizedNameMixin, models.Model):
    name = models.CharField(
        verbose_name=_("recipes__model__ingredient__name"),
        max_length=127,
    )

    class Meta:
        ordering = ["name"]
        verbose_name = _("recipes__model__ingredient__verbose_name")
        verbose_name_plural = _(
            "recipes__model__ingredient__verbose_name_plural",
        )

    def __str__(self):
        return self.name


class Recipe(NormalizedNameMixin, models.Model):
    objects: RecipeManager = RecipeManager()

    name = models.CharField(
        verbose_name=_("recipes__model__recipe__name"),
        max_length=255,
    )
    author = models.ForeignKey(
        User,
        related_name="recipes",
        verbose_name=_("model__foreign__author"),
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(
        verbose_name=_("model__created"),
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        verbose_name=_("model__updated"),
        auto_now=True,
    )
    state = models.CharField(
        max_length=3,
        verbose_name=_("recipes__model__recipe__state"),
        choices=RecipeState.choices,
        default=RecipeState.MODERATED,
    )
    categories = models.ManyToManyField(
        Category,
        related_name="recipes",
        verbose_name=_("model__foreign__categories"),
        blank=True,
    )
    kitchen = models.ForeignKey(
        Kitchen,
        related_name="recipes",
        verbose_name=_("model__foreign__kitchen"),
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    instruction = MDTextField(
        verbose_name=_("recipes__model__recipe__instruction"),
        max_length=8191,
    )
    main_image = models.ImageField(
        verbose_name=_("recipes__model__recipe__main_image"),
        upload_to=RandomFileName("recipes/main_image/"),
        blank=True,
        null=True,
    )
    level = models.IntegerField(
        choices=RecipeLevel.choices,
        verbose_name=_("recipes__model__recipe__level"),
    )
    time = models.PositiveIntegerField(
        verbose_name=_("recipes__model__recipe__time"),
    )

    class Meta:
        verbose_name = _("recipes__model__recipe__verbose_name")
        verbose_name_plural = _("recipes__model__recipe__verbose_name_plural")

    def __str__(self):
        if len(self.name) > 100:
            return self.name[:100] + "..."

        return self.name

    def get_rendered_instruction(self) -> str:
        return render_markdown(self.instruction)

    def get_image_500(self) -> Thumbnail | None:
        if not self.main_image:
            return None

        return get_thumbnail(self.main_image, "500", quality=85)

    def get_image_128x128(self) -> Thumbnail | None:
        if not self.main_image:
            return None

        return get_thumbnail(
            self.main_image,
            "128x128",
            crop="center",
            quality=51,
        )

    def image_tmb(self) -> str:
        if self.main_image:
            return mark_safe(
                f'<img src="{self.get_image_128x128().url}"',
            )

        return _("model__image__no_image")

    image_tmb.short_description = _("model__image__preview")
    image_tmb.allow_tags = True


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="ingredients",
        verbose_name=_("model__foreign__recipe"),
    )
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        verbose_name=_("model__foreign__ingredient"),
    )
    count = models.FloatField(
        verbose_name=_("recipes__model__recipe_ingredient__count"),
        validators=[
            MinValueValidator(0),
        ],
    )
    unit = models.CharField(
        max_length=12,
        verbose_name=_("recipes__model__recipe_ingredient__unit"),
        choices=IngredientUnit.choices,
    )

    class Meta:
        unique_together = ("recipe", "ingredient")
        verbose_name = _("recipes__model__recipe_ingredient__verbose_name")
        verbose_name_plural = _(
            "recipes__model__recipe_ingredient__verbose_name_plural",
        )

    def __str__(self):
        return _("recipes__model__recipe_ingredient__str") % {
            "id": self.id,
            "ingredient": self.ingredient_id,
            "recipe": self.recipe_id,
        }


class RecipeImage(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="images",
        verbose_name=_("model__foreign__recipe"),
    )
    image = models.ImageField(
        upload_to=RandomFileName("recipes/recipe/"),
        verbose_name=_("recipes__model__recipe_image__image"),
    )

    class Meta:
        verbose_name = _("recipes__model__recipe_image__verbose_name")
        verbose_name_plural = _(
            "recipes__model__recipe_image__verbose_name_plural",
        )

    def __str__(self):
        return _("recipes__model__recipe_image__str") % {
            "id": self.id,
            "recipe": self.recipe_id,
        }

    def get_image_500(self) -> Thumbnail | None:
        if not self.image:
            return None

        return get_thumbnail(self.image, "500", quality=85)

    def get_image_128x128(self) -> Thumbnail | None:
        if not self.image:
            return None

        return get_thumbnail(self.image, "128x128", crop="center", quality=51)

    def image_tmb(self) -> str:
        if not self.image:
            return _("model__image__no_image")

        return mark_safe(
            f'<img src="{self.get_image_128x128().url}"',
        )

    image_tmb.short_description = _("model__image__preview")
    image_tmb.allow_tags = True


__all__ = []

recipebook/templates/recipes/main.html
{% extends "base.html" %}
{% load i18n %}

{% comment %} {% translate "login__title" %} {% endcomment %}
{% block content %}
	<h2 class="mt-4">Добро пожаловать!</h2>

	<div class="row justify-content-left">
		<div class="col-12 col-md-6 col-lg-4">
            <a href="{% url 'recipes:search' %}" class="btn btn-primary mt-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                </svg>
                Найти рецепт
            </a>
		</div>
	</div>

    <div>
        <h2 class="mt-4">Самые популярные</h2>
        <div class="row">
            {% for recipe in most_popular_5 %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <img class="card-img-top" src="{{ recipe.get_image_500.url }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.name }}</h5>
                        <p class="card-text">Автор: {{ recipe.author.username }}</p>
                        <a href="{% url 'recipes:recipe' recipe.id %}" class="btn btn-primary">Смотреть</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    <div>

    <div>
        <h2 class="mt-4">Последние добавленныe</h2>
        <div class="row">
            {% for recipe in last_5_recipes %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <img class="card-img-top" src="{{ recipe.get_image_500.url }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.name }}</h5>
                        <p class="card-text">Автор: {{ recipe.author.username }}</p>
                        <a href="{% url 'recipes:recipe' recipe.id %}" class="btn btn-primary">Смотреть</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    <div>
{% endblock %}

recipebook/templates/recipes/recipe.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{{recipe.name}}
{% endblock %}

{% block content %}
	<h2 class="text-center mt-4">{{recipe.name}}</h2>

	<div class="row justify-content-center">
		<div class="col-12 col-md-4 d-grid column-gap-2 bg-body-secondary rounded-2 p-2" style="grid-template-columns: auto 1fr;">
			<h6 class="m-0"></h6>
			<a href="{% url 'recipes:recipe-edit' recipe.id %}">edit</a>
			<h6 class="m-0">main_image</h6>
			<img src="{{recipe.get_image_128x128.url}}" alt="main_image">
			<h6 class="m-0">author</h6>
			<div>{{recipe.author}}</div>
			<h6 class="m-0">created</h6>
			<div>{{recipe.created}}</div>
			<h6 class="m-0">state</h6>
			<div>{{recipe.get_state_display}}</div>
			<h6 class="m-0">categories</h6>
			<ul>
				{% for category in recipe.categories.all %}
				<li>{{category}}</li>
				{% empty %}нету{% endfor %}
			</ul>
			<h6 class="m-0">kitchen</h6>
			<div>{{recipe.kitchen}}</div>
			<h6 class="m-0">level</h6>
			<div>{{recipe.get_level_display}}</div>
			<h6 class="m-0">time</h6>
			<div>{{recipe.time}} мин</div>
			<h6 class="m-0">ingredients</h6>
			<ul>
				{% for ingredient in recipe.ingredients.all %}
				<li>{{ingredient.ingredient}}: {{ingredient.count|floatformat}} {{ingredient.get_unit_display}}</li>
				{% empty %}нету{% endfor %}
			</ul>
		</div>
		<div class="col-12 col-md-6">
			<div class="markdown">{{recipe.get_rendered_instruction|safe}}</div>
			<div class="d-flex align-items-end">
				<div>
					<p class="mb-0">{% blocktranslate count counter=rating_count %}recipe__rating {{counter}}{{ rating }}{% plural %}recipe__rating {{counter}}{{ rating }}{% endblocktranslate %}</p>
					{% if user.is_authenticated %}
					{% if user_rating %}
					<p class="mb-0">{% translate "recipe__user_rating" %} {{ user_rating.value }}</p>
					{% endif %}
					{% translate "recipe__rate" as submit_text_rate %}
					{% include "includes/form.html" with form=rating_form submit_text=submit_text_rate %}
					{% endif %}
				</div>
				{% if user_rating %}
				<div>
					{% translate "recipe__delete_rate" as submit_delete_text %}
					{% include "includes/form.html" with form=delete_rating_form submit_text=submit_delete_text %}
				</div>
				{% endif %}
				{% if user.is_authenticated %}
				<div>
					{% if user_cooked %}
					{% include "includes/form.html" with form=delete_cooked_form submit_text="Убрать отметку о приготовлении" %}
					{% else %}
					{% include "includes/form.html" with form=cooked_form submit_text="Отметить как приготовленное" %}
					{% endif %}
				</div>
				{% endif %}
			</div>
		</div>
		<div class="col-12 col-md-8">
			<h3>Комментарии</h3>
			{% if user.is_authenticated %}
			<div class="my-4 bg-body-secondary p-2 rounded">
				<h5>Ваш комментарии {% if not user_comment %}(новый){% endif %}</h5>
				{{ comment_form.media }}
				{% include "includes/form.html" with form=comment_form %}
				{% if user_comment %}
				{% include "includes/form.html" with form=delete_comment_form submit_text="Удалить комментарии" %}
				{% endif %}
			</div>
			{% endif %}
			<div class="d-flex flex-column gap-2">
				{% for comment in comments %}
				<div class="bg-body-secondary p-2 rounded">
					<div class="d-flex justify-content-between">
						<h5>{{comment.author.username}}</h5>
						<span>{{comment.created}}</span>
					</div>
					<div class="markdown">{{comment.get_rendered_text|safe}}</div>
				</div>
				{% empty %}Нет комментариев{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

recipebook/templates/recipes/recipe_edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
Редактирование: {{recipe.name}}
{% endblock %}

{% block content %}
	<h2 class="text-center mt-4">{{recipe.name}}</h2>

	<div class="row justify-content-center">
		<div class="col-12 col-md-8">
			{{ form.media }}
			{% include "includes/form.html" with form=form %}
		</div>
	</div>
{% endblock %}

recipebook/templates/recipes/search.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
{% translate "recipes__search__title" %}
{% endblock %}

{% block head %}
	<link rel="stylesheet" href="{% static 'css/search.css' %}">
	<script src="{% static 'js/search.js' %}" defer></script>
{% endblock %}

{% block content %}
	<h2 class="text-center mt-4">Поиск</h2>

	<div class="row justify-content-center">
		<div class="col-12 col-lg-8">
			<div class="mb-4 d-grid" style="grid-template-columns: 1fr 1fr;">
				<div>
					<div>
                        <span>Название:</span>
                        <input autocomplete="off" type="text" id="search-name" class="form-control">
					</div>
					<div>
						<span>Содержатся: </span>
						<span class="search-ingredients" id="search-ingredient-include"></span>
					</div>
					<div>
						<span>Исключить: </span>
						<span class="search-ingredients" id="search-ingredient-exclude"></span>
					</div>
				</div>
				<div>
					<span>Ингредиенты:</span>
					<div class="search-container" id="search-ingredient-container">
						<input autocomplete="off" type="text" id="search-ingredient-input" class="form-control ms-2">
						<div class="search" id="search-ingredient-list">
							{% for ingredient in ingredients %}
							<div class="search__item" data-id="{{ingredient.id}}">
								<span>{{ingredient.name}}</span>
								<span class="search__btns">
									<label>
										<input type="checkbox" id="search-ingredient-include-chb">
										<span>искать</span>
									</label>
									<label>
										<input type="checkbox" id="search-ingredient-exclude-chb">
										<span>исключить</span>
									</label>
								</span>
							</div>
							{% endfor %}
							<div style="display: none;">
								<h6 class="m-0">Нет такого ингредиента</h6>
								<a href="/" target="_blank">Запросить его добавление</a>
							</div>
						</div>
					</div>
					<div>
						<span>Категория:</span>
						<select id="search-category">
							<option value="">Любая</option>
							{% for categoriy in categories %}
							<option value="{{categoriy.id}}">{{categoriy.name}}</option>
							{% endfor %}
						</select>
					</div>
					<div>
						<span>Кухня:</span>
						<select id="search-kitchen">
							<option value="">Любая</option>
							{% for kitchen in kitchens %}
							<option value="{{kitchen.id}}">{{kitchen.name}}</option>
							{% endfor %}
						</select>
					</div>
					<div>
						<span>Сложность:</span>
						<select id="search-level">
							<option value="">Любая</option>
							{% for level in levels %}
							<option value="{{level.0}}">{{level.1}}</option>
							{% endfor %}
						</select>
					</div>
				</div>
				<div>
					<button class="btn btn-primary" id="search-btn">Искать!</button>
					<button class="btn btn-secondary " id="search-clear-btn">Очистить поиск</button>
				</div>
			</div>
			<div>
				<span>Сортировка:</span>
				<button class="btn btn-sm btn-link" id="sort-name">По названию</button>
				<button class="btn btn-sm btn-link" id="sort-new">Новые</button>
				<button class="btn btn-sm btn-link" id="sort-easy">Лёгкие</button>
				<button class="btn btn-sm btn-link" id="sort-fast">Быстрые</button>
			</div>
			<div class="d-grid gap-4" style="grid-template-columns: 1fr 1fr;">
				{% for recipe in recipes %}
				<div class="d-grid column-gap-2 bg-body-secondary rounded-2 p-2" style="grid-template-columns: auto auto;">
					<h6 class="m-0">name</h6>
					<a href="{% url 'recipes:recipe' recipe.id %}">{{recipe.name}}</a>
					<h6 class="m-0"></h6>
					<a href="{% url 'recipes:recipe-edit' recipe.id %}">edit</a>
					<h6 class="m-0">main_image</h6>
					<img src="{{recipe.get_image_128x128.url}}" alt="main_image">
					<h6 class="m-0">author</h6>
					<div>{{recipe.author}}</div>
					<h6 class="m-0">created</h6>
					<div>{{recipe.created}}</div>
					<h6 class="m-0">state</h6>
					<div>{{recipe.get_state_display}}</div>
					<h6 class="m-0">categories</h6>
					<ul>
						{% for category in recipe.categories.all %}
						<li>{{category}}</li>
						{% empty %}нету{% endfor %}
					</ul>
					<h6 class="m-0">kitchen</h6>
					<div>{{recipe.kitchen}}</div>
					<h6 class="m-0">level</h6>
					<div>{{recipe.get_level_display}}</div>
					<h6 class="m-0">time</h6>
					<div>{{recipe.time}} мин</div>
					<h6 class="m-0">ingredients</h6>
					<ul>
						{% for ingredient in recipe.ingredients.all %}
						<li>{{ingredient.ingredient}}: {{ingredient.count|floatformat}} {{ingredient.get_unit_display}}</li>
						{% empty %}нету{% endfor %}
					</ul>
				</div>
				{% empty %}
				<h3>Ничего не найдено</h3>
				{% endfor %}
			</div>
			<div class="d-flex align-items-center justify-content-center my-3">
				<span class="step-links" id="pagination">
					{% if page_obj.has_previous %}
						<button class="btn btn-success btn-sm" data-page="1">&laquo; first</button>
						<button class="btn btn-primary btn-sm" data-page="{{ page_obj.previous_page_number }}">previous</button>
					{% endif %}

					<span class="mx-1">
						Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
					</span>

					{% if page_obj.has_next %}
						<button class="btn btn-primary btn-sm" data-page="{{ page_obj.next_page_number }}">next</button>
						<button class="btn btn-success btn-sm" data-page="{{ page_obj.paginator.num_pages }}">last &raquo;</button>
					{% endif %}
				</span>
			</div>
		</div>
	</div>
{% endblock %}